# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diaserial.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 274)
        self.lblSerialFonc = QtWidgets.QLabel(Dialog)
        self.lblSerialFonc.setGeometry(QtCore.QRect(110, 20, 281, 71))
        self.lblSerialFonc.setObjectName("lblSerialFonc")
        self.lblSerialEchou = QtWidgets.QLabel(Dialog)
        self.lblSerialEchou.setGeometry(QtCore.QRect(110, 110, 281, 81))
        self.lblSerialEchou.setObjectName("lblSerialEchou")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblSerialFonc.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#ff55ff;\">Enregistrement completer</span></p></body></html>"))
        self.lblSerialEchou.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#f43009;\">ENREGISTREMENT ECHOUER</span></p></body></html>"))
